### ISSUE TITLE
Better to remove the link to MSVCP110D.dll

### ISSUE THREAD

**Issue by hydra1983** [CRogers/LLVM-Windows-Binaries#1] opened 2013-08-31 04:40 UTC
I got this error when running the tools.

![image](https://f.cloud.github.com/assets/488235/1061697/776b4486-11f7-11e3-9fc8-0cb86121ee42.png)

Thank you.

**Comment by CRogers** [comment] 2013-09-02 00:06
Oops. The solution to this is to compile in Release mode properly but sadly I'm in foreign country on a business trip without a windows machine for the next month or so. Otherwise the stopgap solution would be to download the free version of VS2012 :/

**Comment by hydra1983** [comment] 2013-09-02 02:46
OK, Thank you all the same.
I will try it myself with the help of your "compiling document".

**Comment by CRogers** [comment] 2013-10-01 10:59
I am back in the UK, I will redo the compilation in Release mode sometime in the next few days.

**Comment by picpromusic** [comment] 2013-12-31 08:19
Do you had some cycles left to recompile it?

**Comment by CRogers** [comment] 2014-01-01 12:16
Welp, I suppose I better do this today.

**Comment by CRogers** [comment] 2014-01-01 13:37
Well, I just tried to compile to it in Release mode and there's still a link to `DBGHELP.dll` but the link to `MSVCP110D.dll` seems to have gone. Can you try and run this these as a test, @picpromusic or @hydra1983?:

https://dl.dropboxusercontent.com/u/26776187/llvm-rtdyld.exe
https://dl.dropboxusercontent.com/u/26776187/lli.exe
https://dl.dropboxusercontent.com/u/26776187/llc.exe

If they work then I'll make a new release. Note they will only run on 64 bit windows.

**Comment by semiessessi** [comment] 2014-02-25 14:57
the version in the repo still requires the debug run-time.

we are also now on 3.4

some previous version i'm sure i got from here does not have this problem (i had been using thus far)

for myself i've built a version against the release version and am able to host it somewhere for others, but would rather not pollute the web with duplicates.

if i do that i'd be inclined to remove the dependency on the separate run-time anyway and static link it in and resolve the various duplicate symbol errors i'm sure that will create...

**Comment by semiessessi** [comment] 2014-02-25 14:57
(p.s. i am happy to test any builds you may have on a machine which is lacking the vs 2012 debug run-time)

**Comment by CRogers** [comment] 2014-03-01 12:10
I am happy to give you commit access to this repo to do what you think is right/make any releases. I now have no windows machine so can't do this anymore.

**Comment by semiessessi** [comment] 2014-03-02 16:44
thanks for the reply. if you do i'll get a more friendly version in there asap. :)

**Comment by CRogers** [comment] 2014-03-03 11:28
@semiessessi: You're now a collaborator!

**Comment by semiessessi** [comment] 2014-03-03 19:35
Thanks. I have pushed some changes with a release build of the LLVM 3.4 tools and some updates to the instructions to match.

This means that the issue is resolved in the latest revision (tag v3.4) - it now uses the release .dll from the run-time for VS 2013 (redistributable here: http://www.microsoft.com/en-gb/download/details.aspx?id=40784).

The build process in the documents has been tested with Visual Studio Express 2013 and Windows 8.1.

The tools have been tested by running their help commands and some mild use in a compiler project I am working on. The test suite takes too long to run (hence I selected only the necessary projects to build in VS) but didn't report any obvious fails...

The shared library has only been tested in the most trivial of ways - it would be nice if someone could test it more thoroughly, otherwise I will do so when I have some more spare time for this. :)

**Closed as completed by semiessessi** 2014-03-03 19:35 UTC
